# Site settings
baseURL = "https://alexandru-botorog-portfolio-website.netlify.app"
languageCode = "en-us"
title = "Alexandru Botorog Portfolio Website"
theme = "forty"

# Enter your tracking code to enable Google Analytics
#googleAnalytics = ""

# Enter your disqus shortname to enable comments
#disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Alexandru-Victor Botorog"
  description = "Contains selected code written by Alexandru, as well as personal details and the CV"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  #image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Portfolio"
    subtitle = "Website"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About me"
      url = "about/about_me"

    [[params.navigation.links]]
      name = "CV"
      url = "https://drive.google.com/file/d/1Hzfwj0XfdAdhCdzJWhXNUVWXDqyQR_Xz/view?usp=share_link"

    [[params.navigation.links]]
      name = "Loan Defaults at Lending Club"
      url = "blogs/LogisticWorkshop2022"
      
    [[params.navigation.links]]
      name = "London House Prices"
      url = "blogs/Alexandru_Botorog_Final_Individual_Project"
      
    [[params.navigation.links]]
      name = "Movie Ratings Part 1"
      url = "blogs/AM11_Part1_Alexandru_Botorog"
      
    [[params.navigation.links]]
      name = "Movie Ratings Part 2"
      url = "blogs/Alexandru_Botorog_AM11_2023-Part_2"
      
    [[params.navigation.links]]
      name = "Movie Ratings Part 3"
      url = "blogs/Alexandru_Botorog_AM11_2023-Part_3"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
      #name = "Get Started"
      #url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
      #name = "Log In"
      #url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Alexandru"
    subtitle = "Below you can view my story, CV, and several projets I have undertaken over the years"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "About me"
      subtitle = "A short summary"
      image = "About_Me.png"
      url = "about/about_me"

    [[params.tiles.showcase]]
      title = "CV"
      subtitle = "Education, Experience, and Extracurriculars"
      image = "lbs.jpg"
      url = "https://drive.google.com/file/d/1Hzfwj0XfdAdhCdzJWhXNUVWXDqyQR_Xz/view?usp=share_link"

    [[params.tiles.showcase]]
      title = "Predicting Loan Defaults at Lending Club"
      subtitle = "Logistic Regression"
      image = "peer-to-peer_lending.jpg"
      url = "blogs/LogisticWorkshop2022"

    [[params.tiles.showcase]]
      title = "Predicting London House Prices"
      subtitle = "Linear Regression, Decision Trees, KNN, Random Forests, Gradient Boosting, Stacking"
      image = "London_house.jpg"
      url = "blogs/Alexandru_Botorog_Final_Individual_Project"

    [[params.tiles.showcase]]
      title = "Movies Part 1: Predicting Ratings"
      subtitle = "Collaborative Filtering Methods"
      image = "Movie11.jpg"
      url = "blogs/AM11_Part1_Alexandru_Botorog"
      
    [[params.tiles.showcase]]
      title = "Movies Part 2: Extracting Features from Movie Tags"
      subtitle = "Text Mining & Principal Component Analysis"
      image = "Movie11.jpg"
      url = "blogs/Alexandru_Botorog_AM11_2023-Part_2"  
      
    [[params.tiles.showcase]]
      title = "Movies Part 3: Predicting Ratings using Extracted Features"
      subtitle = "Support Vector Machines & Neural Networks"
      image = "Movie11.jpg"
      url = "blogs/Alexandru_Botorog_AM11_2023-Part_3"
    

    #[[params.tiles.showcase]]
      #title = "Etiam"
      #subtitle = "Feugiat Amet Tempus"
      #image = "pic06.jpg"
      #url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "My coding experience"
    subtitle = """I possess significant coding experience with Python and R 
    and I am able to use them for both regular applications and data analytics. 
    I began using Python in my first academic year at UCL when I took the 
    Introduction to Programming elective. I quickly developed a good 
    understanding of programming algorithms and obtained a mark of 80 in that 
    module. The following summer I took an online course called Introduction to 
    Data Science in Python, which is where my interest in data science
    originated from. The first time I have used R was in my final academic
    year at UCL when I had to estimate the Value-at-Risk (VaR) of an equally 
    weighted portfolio holding two stock indices, S&P500 and DAX, using a Monte 
    Carlo simulation approach based on copula theory. I have since begun using R
    more frequently as part of my Masters in Analytics and Management programme
    at LBS. Other software programmes I have significant experience with include
    Mathematica, Stata, and Excel. By clicking the button below you can see
    some examples of code I have written in R."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "abotorog.mam2023@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44 7713 997648"

    [[params.contact.address]]
    title = "Address"
    street = "8a Westwick Gardens"
    city = "London, W14 0BU"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Alexandru-Victor Botorog"

    # Uses font awesome icons
    #[[params.footer.social]]
     # icon = "fa-twitter"
     # url= "https://www.twitter.com"
     # label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/alex.boto.1/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/alex.boto.1/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/AlexBoto458"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/alexandru-victor-botorog-9a5a34169/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
